import { Circle, icons, type LucideIcon } from 'lucide-react'

// WHY: AI agents frequently hallucinate icon names; this map converts AI outputs to actual Lucide icons
// e.g., AI writes "wiring" → "Cable", "networking" → "Network"
const AI_ICON_ALIASES: Record<string, string> = {
  wiring: 'Cable',
  wire: 'Cable',
  cables: 'Cable',
  networking: 'Network',
  network: 'Network',
  connectivity: 'Cable',
  connection: 'Link',
  connected: 'Link',
  ethernet: 'Cable',
  frontend: 'Monitor',
  'front-end': 'Monitor',
  ui: 'Monitor',
  interface: 'LayoutDashboard',
  client: 'Monitor',
  web: 'Globe',
  website: 'Globe',
  browser: 'Globe',
  display: 'Monitor',
  screen: 'Monitor',
  view: 'Eye',
  backend: 'Server',
  'back-end': 'Server',
  server: 'Server',
  api: 'Plug',
  service: 'Server',
  microservice: 'Boxes',
  services: 'Boxes',
  database: 'Database',
  db: 'Database',
  data: 'Database',
  storage: 'HardDrive',
  cache: 'Database',
  persistence: 'Save',
  testing: 'FlaskConical',
  test: 'FlaskConical',
  qa: 'CircleCheck',
  quality: 'Award',
  validation: 'SquareCheck',
  verification: 'CircleCheck',
  design: 'Palette',
  ux: 'Pencil',
  graphics: 'Palette',
  art: 'Palette',
  style: 'Palette',
  theme: 'Palette',
  branding: 'Palette',
  security: 'Shield',
  auth: 'Lock',
  authentication: 'Lock',
  authorization: 'Key',
  permissions: 'Key',
  encryption: 'Lock',
  crypto: 'Lock',
  devops: 'Cloud',
  deployment: 'Rocket',
  deploy: 'Rocket',
  cicd: 'GitBranch',
  'ci/cd': 'GitBranch',
  pipeline: 'GitBranch',
  automation: 'Zap',
  infrastructure: 'Server',
  infra: 'Server',
  cloud: 'Cloud',
  hosting: 'Cloud',
  containers: 'Box',
  container: 'Box',
  docker: 'Box',
  kubernetes: 'Boxes',
  k8s: 'Boxes',
  monitoring: 'Eye',
  monitor: 'Eye',
  observability: 'Eye',
  logs: 'FileText',
  logging: 'FileText',
  metrics: 'ChartLine',
  analytics: 'ChartBar',
  tracing: 'GitBranch',
  docs: 'BookOpen',
  documentation: 'BookOpen',
  readme: 'FileText',
  wiki: 'BookOpen',
  manual: 'BookOpen',
  guide: 'BookOpen',
  marketing: 'Megaphone',
  communication: 'MessageCircle',
  messaging: 'MessageSquare',
  chat: 'MessageCircle',
  email: 'Mail',
  notifications: 'Bell',
  alerts: 'CircleAlert',
  development: 'Code',
  dev: 'Code',
  coding: 'Code',
  programming: 'Code',
  code: 'Code',
  terminal: 'Terminal',
  console: 'Terminal',
  shell: 'Terminal',
  cli: 'Terminal',
  git: 'GitBranch',
  vcs: 'GitBranch',
  version: 'GitBranch',
  repository: 'FolderGit',
  repo: 'FolderGit',
  build: 'Hammer',
  compile: 'Hammer',
  bundler: 'Package',
  webpack: 'Package',
  menu: 'Menu',
  navigation: 'Menu',
  nav: 'Menu',
  hamburger: 'Menu',
  sidebar: 'PanelLeft',
  add: 'Plus',
  create: 'Plus',
  new: 'Plus',
  edit: 'Pencil',
  modify: 'Pencil',
  update: 'RefreshCw',
  delete: 'Trash2',
  remove: 'Trash2',
  trash: 'Trash2',
  save: 'Save',
  download: 'Download',
  upload: 'Upload',
  send: 'Send',
  submit: 'Send',
  search: 'Search',
  find: 'Search',
  filter: 'ListFilter',
  sort: 'ArrowUpDown',
  settings: 'Settings',
  config: 'Settings',
  configuration: 'Settings',
  preferences: 'Settings',
  options: 'Settings',
  gear: 'Settings',
  cog: 'Settings',
  file: 'File',
  files: 'Files',
  folder: 'Folder',
  directory: 'Folder',
  document: 'FileText',
  documents: 'FileText',
  image: 'Image',
  images: 'Image',
  photo: 'Image',
  picture: 'Image',
  video: 'Video',
  audio: 'Music',
  media: 'Image',
  user: 'User',
  users: 'Users',
  account: 'User',
  profile: 'User',
  avatar: 'User',
  person: 'User',
  business: 'Briefcase',
  commerce: 'ShoppingCart',
  shop: 'ShoppingCart',
  store: 'ShoppingCart',
  cart: 'ShoppingCart',
  payment: 'CreditCard',
  billing: 'DollarSign',
  invoice: 'Receipt',
  time: 'Clock',
  clock: 'Clock',
  schedule: 'Calendar',
  calendar: 'Calendar',
  date: 'Calendar',
  timer: 'Timer',
  success: 'CircleCheck',
  error: 'CircleX',
  warning: 'TriangleAlert',
  info: 'Info',
  help: 'CircleQuestionMark',
  question: 'CircleQuestionMark',
  performance: 'Zap',
  speed: 'Zap',
  fast: 'Zap',
  optimization: 'Zap',
  optimize: 'Zap',
  mobile: 'Smartphone',
  phone: 'Smartphone',
  tablet: 'Tablet',
  desktop: 'Monitor',
  laptop: 'Laptop',
  device: 'Smartphone',
  share: 'Share2',
  social: 'Share2',
  like: 'Heart',
  favorite: 'Heart',
  star: 'Star',
  location: 'MapPin',
  map: 'Map',
  place: 'MapPin',
  gps: 'MapPin',
  power: 'Power',
  start: 'Play',
  stop: 'Square',
  pause: 'Pause',
  restart: 'RotateCcw',
  input: 'Download',
  output: 'Upload',
  import: 'Download',
  export: 'Upload',
  transfer: 'ArrowLeftRight',
  sync: 'RefreshCw',
  organization: 'Building',
  company: 'Building',
  team: 'Users',
  group: 'Users',
  learning: 'GraduationCap',
  education: 'GraduationCap',
  course: 'BookOpen',
  tutorial: 'BookOpen',
  plugin: 'Plug',
  plugins: 'Plug',
  extension: 'Puzzle',
  addon: 'Puzzle',
  module: 'Box',
  report: 'ChartBar',
  reports: 'ChartBar',
  dashboard: 'LayoutDashboard',
  chart: 'ChartBar',
  graph: 'ChartLine',
  task: 'SquareCheck',
  tasks: 'ListChecks',
  todo: 'SquareCheck',
  checklist: 'ListChecks',
  accessibility: 'Accessibility',
  a11y: 'Accessibility',
  language: 'Languages',
  translate: 'Languages',
  translation: 'Languages',
  i18n: 'Languages',
  backup: 'Archive',
  restore: 'RotateCcw',
  recovery: 'RotateCcw',
  event: 'Zap',
  trigger: 'Zap',
  tag: 'Tag',
  tags: 'Tags',
  label: 'Tag',
  labels: 'Tags',
  print: 'Printer',
  printer: 'Printer',
  copy: 'Copy',
  paste: 'Clipboard',
  clipboard: 'Clipboard',
  undo: 'Undo',
  redo: 'Redo',
  visible: 'Eye',
  hidden: 'EyeOff',
  show: 'Eye',
  hide: 'EyeOff',
  lock: 'Lock',
  locked: 'Lock',
  unlock: 'LockOpen',
  unlocked: 'LockOpen',
  public: 'Globe',
  private: 'Lock',
  link: 'Link',
  unlink: 'Unlink',
  url: 'Link',
  expand: 'ChevronDown',
  collapse: 'ChevronUp',
  refresh: 'RefreshCw',
  reload: 'RefreshCw',
  close: 'X',
  exit: 'X',
  cancel: 'X',
  home: 'House',
  house: 'House',
  maximize: 'Maximize',
  minimize: 'Minimize',
  fullscreen: 'Maximize2',
  volume: 'Volume2',
  mute: 'VolumeX',
  sound: 'Volume2',
  brightness: 'Sun',
  dark: 'Moon',
  light: 'Sun',
  battery: 'Battery',
  charging: 'BatteryCharging',
  wifi: 'Wifi',
  signal: 'Signal',
  bluetooth: 'Bluetooth',
  usb: 'Usb',
  camera: 'Camera',
  webcam: 'Camera',
  microphone: 'Mic',
  mic: 'Mic',
  external: 'ExternalLink',
  internal: 'House',
  webhook: 'Webhook',
  rest: 'Plug',
  graphql: 'Network',
  grpc: 'Network',
  soap: 'Cloud',
  lambda: 'Zap',
  function: 'Code',
  serverless: 'Cloud',
  edge: 'Zap',
  cdn: 'Globe',
  dns: 'Globe',
  ssl: 'Lock',
  firewall: 'Shield',
  loadbalancer: 'Scale',
  queue: 'List',
  stream: 'Radio',
  batch: 'Layers',
  cron: 'Clock',
  production: 'Rocket',
  staging: 'FlaskConical',
  local: 'House',
  main: 'GitBranch',
  master: 'GitBranch',
  feature: 'GitBranch',
  bugfix: 'Bug',
  hotfix: 'Flame',
  bug: 'Bug',
  issue: 'CircleAlert',
  ticket: 'Ticket',
  workflow: 'GitBranch',
  process: 'GitBranch',
  flow: 'GitBranch'
}

export function resolveIcon(name: string): LucideIcon {
  if (!name) {
    console.warn('resolveIcon called with empty name')
    return Circle
  }

  if (icons[name as keyof typeof icons]) {
    return icons[name as keyof typeof icons] as LucideIcon
  }

  const normalized = name.toLowerCase().trim()
  const aliasMatch = AI_ICON_ALIASES[normalized]

  if (aliasMatch && icons[aliasMatch as keyof typeof icons]) {
    console.log(`✅ Icon resolved: "${name}" → "${aliasMatch}" (alias)`)
    return icons[aliasMatch as keyof typeof icons] as LucideIcon
  }

  console.warn(`❌ Icon not found for: "${name}", falling back to Circle`)
  return Circle
}

// WHY: Dev validation ensures AI-generated aliases reference real Lucide icons
if (import.meta.env.DEV) {
  const invalidIcons: string[] = []

  for (const [alias, iconName] of Object.entries(AI_ICON_ALIASES)) {
    if (!icons[iconName as keyof typeof icons]) {
      invalidIcons.push(`"${alias}" → "${iconName}" (DOES NOT EXIST)`)
    }
  }

  if (invalidIcons.length > 0) {
    console.error('❌ Icon Registry Validation Failed!')
    console.error(`Found ${invalidIcons.length} hallucinated icon names:\n`)
    for (const err of invalidIcons) {
      console.error(`  ${err}`)
    }
    throw new Error(
      `Icon registry contains ${invalidIcons.length} non-existent icons. Fix AI_ICON_ALIASES in iconRegistry.ts`
    )
  }
}
