# Ralph Loop development commands
# Run with: just <command>
# Install just: cargo install just

set shell := ["bash", "-cu"]

# Generate a discipline portrait (production, 28 steps)
generate-discipline-image STACK DISCIPLINE:
    cargo run -p predefined-disciplines --bin generate-discipline-image -- {{STACK}} {{DISCIPLINE}}

# Generate a discipline portrait (test, 1 step)
generate-discipline-image-test STACK DISCIPLINE:
    cargo run -p predefined-disciplines --bin generate-discipline-image -- --test {{STACK}} {{DISCIPLINE}}

# Default recipe: show available commands
default:
    @just --list

# === Development ===

# Start development server (frontend + backend hot reload)
dev:
    bun tauri dev

# Start frontend dev server only
dev-frontend:
    bun dev

# Start development server with a mock project (skips project picker)
dev-mock FIXTURE:
    #!/usr/bin/env bash
    # Check if mock directory exists at all
    if [ ! -d "mock" ]; then
        echo "Mock directory not found. Creating from fixtures..."
        just reset-mock
    fi

    # Try exact match first
    if [ -d "mock/{{FIXTURE}}" ]; then
        PROJECT_DIR="mock/{{FIXTURE}}"
    else
        # Try prefix match (e.g., "01" matches "01-initialized-project")
        MATCHES=(mock/{{FIXTURE}}*/)
        if [ ${#MATCHES[@]} -eq 1 ] && [ -d "${MATCHES[0]}" ]; then
            PROJECT_DIR="${MATCHES[0]}"
            echo "✓ Found: $(basename "$PROJECT_DIR")"
        elif [ ${#MATCHES[@]} -gt 1 ]; then
            echo "❌ Multiple matches found for '{{FIXTURE}}':"
            for m in "${MATCHES[@]}"; do
                echo "  - $(basename "$m")"
            done
            exit 1
        else
            echo "❌ No mock project found matching '{{FIXTURE}}'"
            echo "Available projects:"
            ls -1 mock/
            exit 1
        fi
    fi

    bun tauri dev -- -- --project {{justfile_directory()}}/"$PROJECT_DIR"

# Run cargo check (fast compilation check)
check:
    cargo check --manifest-path src-tauri/Cargo.toml

# Run lints (Rust + TypeScript)
lint:
    cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings
    oxlint src
    bunx biome lint src

# Fix linting issues automatically
lint-fix:
    bunx biome lint --write src

# Format all code (Rust + TypeScript)
fmt:
    cargo fmt --manifest-path src-tauri/Cargo.toml
    bunx biome format --write src

# Check formatting without writing
fmt-check:
    cargo fmt --manifest-path src-tauri/Cargo.toml --check
    bunx biome format src

# Run all checks (lint + format)
check-all: lint fmt-check

# === Testing ===

# Run all tests
test: test-rust test-frontend

# Run Rust tests
test-rust:
    cargo test --manifest-path src-tauri/Cargo.toml

# Run frontend unit tests
test-frontend:
    bun test:run

# Run E2E tests (requires built frontend)
test-e2e:
    bun test:e2e

# Run visual regression tests
test-visual:
    bun test:visual

# Run chaos/monkey tests
test-monkey:
    bun test:monkey

# Update visual test snapshots
test-visual-update:
    bunx playwright test e2e/visual/ --update-snapshots

# === Building ===

# Build release binary (optimized for Alder Lake)
build:
    bun tauri build

# Build debug binary (faster compilation)
build-debug:
    bun tauri build --debug

# Build frontend only
build-frontend:
    bun build

# Clean build artifacts
clean:
    cargo clean --manifest-path src-tauri/Cargo.toml
    rm -rf dist/

# === Release ===

# Build all Linux packages (deb, rpm, appimage)
release-linux:
    bun tauri build --bundles deb,rpm,appimage

# === Utilities ===

# Install Playwright browsers
playwright-install:
    bunx playwright install --with-deps

# Check if mold linker is installed
check-mold:
    @which mold > /dev/null && echo "✓ mold linker installed" || echo "✗ mold not found - install with: sudo dnf install mold"

# Show system info relevant to development
sysinfo:
    @echo "=== CPU ==="
    @lscpu | grep "Model name"
    @echo "\n=== Memory ==="
    @free -h | head -2
    @echo "\n=== GPU ==="
    @nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null || echo "No NVIDIA GPU"
    @echo "\n=== Rust ==="
    @rustc --version
    @echo "\n=== Node ==="
    @node --version

# Open project in VS Code
code:
    code .

# Watch for file changes and run tests
watch-test:
    cargo watch --manifest-path src-tauri/Cargo.toml -x test

# Generate TypeScript types from Rust via ts-rs (single file, no barrel)
types:
    #!/usr/bin/env bash
    rm -rf target/ts-bindings
    cargo test --workspace -- export_bindings 2>/dev/null || true
    echo '// Auto-generated by ts-rs — do not edit. Regenerate: just types' > src/types/generated.ts
    grep -hvE '^(import type|//)' target/ts-bindings/*.ts | sed '/^\/\*\*/,/\*\//d' | grep -v '^$' >> src/types/generated.ts
    bunx biome check --write --unsafe src/types/generated.ts

# Check if generated types are up to date
types-check:
    #!/usr/bin/env bash
    just types
    if ! git diff --quiet src/types/generated.ts; then
        echo "❌ Generated types are stale. Run 'just types' and commit."
        exit 1
    fi

# === Mock Test Data ===

# Reset mock directory from fixtures (copies fixtures → mock, makes .ralph visible)
reset-mock:
    @bash scripts/reset-mock.sh

# List available mock projects
list-mock:
    #!/usr/bin/env bash
    if [ ! -d "mock" ]; then
        echo "No mock directory found. Run 'just reset-mock' first."
        exit 1
    fi
    echo "Available mock projects:"
    for f in mock/*/; do
        name=$(basename "$f")
        db="${f}.ralph/db/ralph.db"
        if [ -f "$db" ]; then
            title=$(sqlite3 "$db" "SELECT title FROM metadata LIMIT 1;" 2>/dev/null || echo "N/A")
            tasks=$(sqlite3 "$db" "SELECT COUNT(*) FROM tasks;" 2>/dev/null || echo "0")
            echo "  $name: $tasks tasks - $title"
        elif [ -d "${f}.ralph" ]; then
            echo "  $name: (no database)"
        fi
    done

# === Fixtures (Read-only reference data) ===

# List available fixtures (note: use mock/ for testing)
list-fixtures:
    #!/usr/bin/env bash
    echo "Available fixtures (read-only, use 'just reset-mock' for testing):"
    for f in fixtures/*/; do
        name=$(basename "$f")
        db="${f}.undetect-ralph/db/ralph.db"
        if [ -f "$db" ]; then
            title=$(sqlite3 "$db" "SELECT title FROM metadata LIMIT 1;" 2>/dev/null || echo "N/A")
            tasks=$(sqlite3 "$db" "SELECT COUNT(*) FROM tasks;" 2>/dev/null || echo "0")
            echo "  $name: $tasks tasks - $title"
        elif [ -d "${f}.undetect-ralph" ]; then
            echo "  $name: (no database)"
        fi
    done
