/// Returns bash functions for extracting JSON-RPC request IDs and escaping
/// strings for JSON embedding.
pub fn id_extractor() -> &'static str {
    r#"# Extract JSON-RPC request ID from a line
extract_id() {
    local line="$1"
    local id=""
    # Match "id": followed by a number or quoted string
    if [[ "$line" =~ \"id\"[[:space:]]*:[[:space:]]*([0-9]+) ]]; then
        id="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ \"id\"[[:space:]]*:[[:space:]]*\"([^\"]+)\" ]]; then
        id="\"${BASH_REMATCH[1]}\""
    else
        id="null"
    fi
    echo "$id"
}

# Escape a string for safe JSON embedding
json_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    s="${s//$'\t'/\\t}"
    s="${s//$'\r'/}"
    echo "$s"
}
"#
}

/// Returns the bash shebang, MCP initialize handler, and notifications
/// boilerplate that begins every generated MCP script.
pub fn mcp_header() -> &'static str {
    r#"#!/usr/bin/env bash
set -euo pipefail

# MCP stdio server — reads JSON-RPC from stdin, writes responses to stdout.
# Generated by Ralph prompt-builder. Do not edit.

handle_initialize() {
    local id="$1"
    cat <<EOJSON
{"jsonrpc":"2.0","id":${id},"result":{"protocolVersion":"2024-11-05","capabilities":{"tools":{},"resources":{}},"serverInfo":{"name":"ralph-mcp","version":"0.1.0"}}}
EOJSON
}

handle_notification() {
    # Notifications (initialized, cancelled, etc.) require no response.
    :
}

"#
}
