// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeatureComment = {
  id: number
  category: string
  discipline?: string
  agent_task_id?: number
  body: string
  summary?: string
  reason?: string
  source_iteration?: number
  created?: string
  updated?: string
}
