// Auto-generated by ts-rs — do not edit. Regenerate: just types
export type CommentAuthor = 'human' | 'agent'
export type DisciplineConfig = {
  name: string
  displayName: string
  icon: string
  color: string
  acronym: string
  systemPrompt?: string
  skills: string[]
  conventions?: string
  mcpServers: McpServerConfigData[]
}
export type FeatureData = {
  name: string
  displayName: string
  acronym: string
  description?: string
  created?: string
  knowledgePaths: string[]
  contextFiles: string[]
  architecture?: string
  boundaries?: string
  learnings: FeatureLearningData[]
  dependencies: string[]
}
export type FeatureLearningData = {
  text: string
  reason?: string
  source: string
  taskId?: number
  iteration?: number
  created: string
  hitCount: number
  reviewed: boolean
  reviewCount: number
}
export type FeatureLearning = {
  text: string
  reason?: string
  source: LearningSource
  task_id?: number
  iteration?: number
  created: string
  hit_count: number
  reviewed: boolean
  review_count: number
}
export type GroupStats = {
  name: string
  displayName: string
  total: number
  done: number
  pending: number
  inProgress: number
  blocked: number
  skipped: number
}
export type InferredTaskStatus = 'ready' | 'waiting_on_deps' | 'externally_blocked' | 'in_progress' | 'done' | 'skipped'
export type LearningSource = 'auto' | 'agent' | 'human' | 'opus_reviewed'
export type McpServerConfigData = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type McpServerConfig = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type Priority = 'low' | 'medium' | 'high' | 'critical'
export type ProjectInfo = { title: string; description?: string; created?: string }
export type ProjectProgress = { totalTasks: number; doneTasks: number; progressPercent: number }
export type PromptPreviewSection = { name: string; content: string }
export type PromptPreview = { sections: PromptPreviewSection[]; fullPrompt: string }
export type RalphProject = { name: string; path: string }
export type RecipeConfigData = {
  name: string
  baseRecipe: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
  created?: string
  updated?: string
}
export type RecipeConfigInput = {
  name: string
  baseRecipe: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
}
export type SectionConfig = { name: string; enabled: boolean; instructionOverride?: string }
export type SectionInfo = {
  name: string
  display_name: string
  description: string
  category: string
  is_instruction: boolean
}
export type SectionSettingsData = { enabled: boolean; instructionOverride?: string }
export type TaskComment = { id: number; author: CommentAuthor; agent_task_id?: number; body: string; created?: string }
export type TaskProvenance = 'agent' | 'human' | 'system'
export type TaskStatus = 'pending' | 'in_progress' | 'done' | 'blocked' | 'skipped'
export type Task = {
  id: number
  feature: string
  discipline: string
  title: string
  description?: string
  status: TaskStatus
  inferredStatus: InferredTaskStatus
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  blockedBy?: string
  created?: string
  updated?: string
  completed?: string
  acceptanceCriteria: string[]
  contextFiles: string[]
  outputArtifacts: string[]
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  comments: TaskComment[]
  featureDisplayName: string
  featureAcronym: string
  disciplineDisplayName: string
  disciplineAcronym: string
  disciplineIcon: string
  disciplineColor: string
}
