// Auto-generated by ts-rs — do not edit. Regenerate: just types
export type CropBoxData = { x: number; y: number; w: number; h: number }
export type DisciplineConfig = {
  name: string
  displayName: string
  icon: string
  color: string
  acronym: string
  description?: string
  systemPrompt?: string
  skills: string[]
  conventions?: string
  mcpServers: McpServerConfigData[]
  stackId?: number
  imagePath?: string
  crops?: DisciplineCropsData
  imagePrompt?: DisciplineImagePromptData
}
export type DisciplineCropsData = {
  face: CropBoxData
  card: CropBoxData
  upperbody?: CropBoxData
  portrait?: CropBoxData
  landscape?: CropBoxData
  strip?: CropBoxData
}
export type DisciplineImagePromptData = { positive: string; negative: string }
export type FeatureCommentData = {
  id: number
  category: string
  discipline?: string
  agentTaskId?: number
  body: string
  summary?: string
  reason?: string
  sourceIteration?: number
  created?: string
  updated?: string
}
export type FeatureComment = {
  id: number
  category: string
  discipline?: string
  agent_task_id?: number
  body: string
  summary?: string
  reason?: string
  source_iteration?: number
  created?: string
  updated?: string
}
export type FeatureData = {
  name: string
  displayName: string
  acronym: string
  description?: string
  created?: string
  knowledgePaths: string[]
  contextFiles: string[]
  dependencies: string[]
  status: string
  comments: FeatureCommentData[]
}
export type FeatureLearning = {
  text: string
  reason?: string
  source: LearningSource
  task_id?: number
  iteration?: number
  created: string
  hit_count: number
  reviewed: boolean
  review_count: number
}
export type FeatureStatus = 'active' | 'archived'
export type GroupStats = {
  name: string
  displayName: string
  total: number
  draft: number
  done: number
  pending: number
  inProgress: number
  blocked: number
  skipped: number
}
export type LearningSource = 'auto' | 'agent' | 'human' | 'opus_reviewed'
export type McpServerConfigData = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type McpServerConfig = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type Priority = 'low' | 'medium' | 'high' | 'critical'
export type ProjectInfo = { title: string; description?: string; created?: string }
export type ProjectProgress = { totalTasks: number; doneTasks: number; progressPercent: number }
export type PromptPreviewSection = { name: string; content: string }
export type PromptPreview = { sections: PromptPreviewSection[]; fullPrompt: string }
export type RalphProject = { name: string; path: string }
export type RecipeConfigData = {
  name: string
  baseRecipe: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
  created?: string
  updated?: string
}
export type RecipeConfigInput = {
  name: string
  baseRecipe: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
}
export type SectionConfig = { name: string; enabled: boolean; instructionOverride?: string }
export type SectionInfo = {
  name: string
  display_name: string
  description: string
  category: string
  is_instruction: boolean
}
export type SectionSettingsData = { enabled: boolean; instructionOverride?: string }
export type StackMetadataData = {
  stackId: number
  name: string
  description: string
  philosophy: string
  visualIdentity: VisualIdentityData
  whenToUse: string[]
  disciplineCount: number
  characteristics: string[]
}
export type TaskComment = {
  id: number
  discipline?: string
  agent_task_id?: number
  priority?: string
  body: string
  created?: string
}
export type TaskProvenance = 'agent' | 'human' | 'system'
export type TaskStatus = 'draft' | 'pending' | 'in_progress' | 'done' | 'blocked' | 'skipped'
export type Task = {
  id: number
  feature: string
  discipline: string
  title: string
  description?: string
  status: TaskStatus
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  blockedBy?: string
  created?: string
  updated?: string
  completed?: string
  acceptanceCriteria: string[]
  contextFiles: string[]
  outputArtifacts: string[]
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  pseudocode?: string
  enrichedAt?: string
  comments: TaskComment[]
  featureDisplayName: string
  featureAcronym: string
  disciplineDisplayName: string
  disciplineAcronym: string
  disciplineIcon: string
  disciplineColor: string
}
export type VisualIdentityData = { style: string; theme: string; tone: string; references: string }
