// Auto-generated by ts-rs — do not edit. Regenerate: just types
export type AgentSession = {
  id: string
  sessionNumber: number
  kind: string
  startedBy: string
  taskId?: number
  agent?: string
  model?: string
  launchCommand?: string
  postStartPreamble?: string
  initPrompt?: string
  started?: string
  ended?: string
  exitCode?: number
  closingVerb?: string
  status: string
  promptHash?: string
  outputBytes?: number
  errorText?: string
}
export type AgentSessionCreateInput = {
  id: string
  kind: string
  taskId?: number
  agent?: string
  model?: string
  launchCommand?: string
  postStartPreamble?: string
  initPrompt?: string
}
export type AgentSessionUpdateInput = {
  id: string
  kind?: string
  taskId?: number
  agent?: string
  model?: string
  launchCommand?: string
  postStartPreamble?: string
  initPrompt?: string
  ended?: string
  exitCode?: number
  closingVerb?: string
  status?: string
  promptHash?: string
  outputBytes?: number
  errorText?: string
}
export type AgentSessionsByIdArgs = { id: string }
export type BackendDiagnosticEvent = { level: BackendDiagnosticLevel; source: string; code: string; message: string }
export type BackendDiagnosticLevel = 'warning' | 'error'
export type CropBoxData = { x: number; y: number; w: number; h: number }
export type DisciplineConfig = {
  id: number
  name: string
  displayName: string
  icon: string
  color: string
  acronym: string
  description?: string
  systemPrompt?: string
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  skills: string[]
  conventions?: string
  mcpServers: McpServerConfigData[]
  stackId?: number
  imagePath?: string
  crops?: DisciplineCropsData
  imagePrompt?: DisciplineImagePromptData
  taskTemplates: DisciplineTaskTemplateData[]
}
export type DisciplineCropsData = {
  face: CropBoxData
  card: CropBoxData
  upperbody?: CropBoxData
  portrait?: CropBoxData
  landscape?: CropBoxData
  strip?: CropBoxData
}
export type DisciplineImagePromptData = { positive: string; negative: string }
export type DisciplineTaskTemplateData = {
  id: number
  title: string
  description?: string
  priority?: string
  hints?: string
  estimatedTurns?: number
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  pseudocode?: string
  created?: string
  updated?: string
  pulledCount: number
}
export type DisciplinesCreateArgs = {
  name: string
  displayName: string
  acronym: string
  icon: string
  color: string
  systemPrompt?: string
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  skills: string[]
  conventions?: string
  mcpServers: McpServerConfigData[]
}
export type DisciplinesCroppedImageGetArgs = { disciplineName: string; crop: CropBoxData; label: string }
export type DisciplinesDeleteArgs = { name: string }
export type DisciplinesImageDataGetArgs = { disciplineName: string }
export type DisciplinesUpdateArgs = {
  name: string
  displayName: string
  acronym: string
  icon: string
  color: string
  systemPrompt?: string
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  skills: string[]
  conventions?: string
  mcpServers: McpServerConfigData[]
}
export type FeatureLearning = {
  text: string
  reason?: string
  source: LearningSource
  taskId?: number
  iteration?: number
  created: string
  hitCount: number
  reviewed: boolean
  reviewCount: number
}
export type GroupStats = {
  name: string
  displayName: string
  total: number
  draft: number
  done: number
  pending: number
  inProgress: number
  blocked: number
  skipped: number
}
export type LearningSource = 'auto' | 'agent' | 'human' | 'opus_reviewed'
export type McpServerConfig = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type McpServerConfigData = { name: string; command: string; args: string[]; env: { [key in string]: string } }
export type Priority = 'low' | 'medium' | 'high' | 'critical'
export type ProjectInfo = { title: string; description?: string; created?: string }
export type ProjectInitializeArgs = { path: string; projectTitle: string; stack: number }
export type ProjectLockSetArgs = { path: string }
export type ProjectProgress = { totalTasks: number; doneTasks: number; progressPercent: number }
export type ProjectScanArgs = { rootDir?: string }
export type ProjectValidatePathArgs = { path: string }
export type PromptBuilderConfigData = {
  name: string
  basePrompt: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
  created?: string
  updated?: string
}
export type PromptBuilderConfigDeleteArgs = { name: string }
export type PromptBuilderConfigGetArgs = { name: string }
export type PromptBuilderConfigInput = {
  name: string
  basePrompt: string
  sectionOrder: string[]
  sections: { [key in string]: SectionSettingsData }
}
export type PromptBuilderConfigSaveArgs = { config: PromptBuilderConfigInput }
export type PromptBuilderPreviewArgs = { sections: SectionConfig[]; userInput?: string }
export type PromptPreview = { sections: PromptPreviewSection[]; fullPrompt: string }
export type PromptPreviewSection = { name: string; content: string }
export type ProtocolVersionInfo = { protocolVersion: number }
export type PtyClosedEvent = { sessionId: string; exitCode: number }
export type PtyOutputEvent = { sessionId: string; seq: number; data: string }
export type RalphError = {
  code: number
  message: string
  location: RalphErrorLocation
  context: RalphErrorContextItem[]
  hint?: string
}
export type RalphErrorContextItem = { key: string; value: unknown }
export type RalphErrorLocation = { file: string; line: number; column: number }
export type RalphProject = { name: string; path: string }
export type RecentProject = { path: string; name: string; lastOpened: string }
export type RemoteConnectArgs = { wsUrl: string }
export type RemoteConnectResult = { wsUrl: string; protocol: ProtocolVersionInfo }
export type RemoteEventFrame =
  | { event: 'backend-diagnostic'; payload: BackendDiagnosticEvent }
  | { event: 'terminal:output'; payload: PtyOutputEvent }
  | { event: 'terminal:closed'; payload: PtyClosedEvent }
export type RemoteSshAuthMode = 'key' | 'password'
export type RemoteSshConnectArgs = {
  host: string
  username: string
  sshPort: number
  remotePort: number
  authMode: RemoteSshAuthMode
  identityFile?: string
  password?: string
  keyPassphrase?: string
  knownHostsFile?: string
}
export type RemoteSshConnectResult = {
  wsUrl: string
  protocol: ProtocolVersionInfo
  sshSessionId: number
  host: string
  username: string
  sshPort: number
  remotePort: number
  authMode: RemoteSshAuthMode
  transportKind: RemoteSshTransportKind
  activeProfileId?: string
  identityFile?: string
  knownHostsFile?: string
}
export type RemoteSshHostKeyChallenge = {
  challengeId: string
  host: string
  sshPort: number
  algorithm: string
  fingerprintSha256: string
  knownHostsTargetPath: string
  expiresAt: string
}
export type RemoteSshHostKeyChallengeApproveArgs = { challengeId: string }
export type RemoteSshHostKeyChallengeRejectArgs = { challengeId: string }
export type RemoteSshIdentityImportArgs = {
  profileId: string
  fileName: string
  bytesBase64: string
  passphrase?: string
  savePassphrase: boolean
}
export type RemoteSshIdentityImportResult = { identityRef: string }
export type RemoteSshProfile = {
  id: string
  name: string
  host: string
  username: string
  sshPort: number
  remotePort: number
  authMode: RemoteSshAuthMode
  identityFile?: string
  identityRef?: string
  knownHostsFile?: string
  autoReconnectEnabled: boolean
  lastUsedAt?: string
}
export type RemoteSshProfileConnectArgs = { profileId: string; password?: string; keyPassphrase?: string }
export type RemoteSshProfileDeleteArgs = { profileId: string }
export type RemoteSshProfileSetLastUsedArgs = { profileId: string }
export type RemoteSshProfileUpsertArgs = {
  id?: string
  name: string
  host: string
  username: string
  sshPort: number
  remotePort: number
  authMode: RemoteSshAuthMode
  identityFile?: string
  identityRef?: string
  knownHostsFile?: string
  autoReconnectEnabled: boolean
  password?: string
  keyPassphrase?: string
  savePassword: boolean
  saveKeyPassphrase: boolean
}
export type RemoteSshStatus = {
  active: boolean
  wsUrl?: string
  sshSessionId?: number
  activeProfileId?: string
  host?: string
  username?: string
  sshPort?: number
  remotePort?: number
  authMode?: RemoteSshAuthMode
  transportKind?: RemoteSshTransportKind
  identityFile?: string
  knownHostsFile?: string
}
export type RemoteSshTransportKind = 'stream' | 'tcp_loopback'
export type RemoteStatus = { connected: boolean; wsUrl?: string; protocol?: ProtocolVersionInfo }
export type RemoteWireFrame =
  | { type: 'rpc-request'; id: number; command: string; payload: unknown }
  | { type: 'rpc-ok'; id: number; result: unknown }
  | { type: 'rpc-err'; id: number; error: RalphError }
  | ({ type: 'event' } & (
      | { event: 'backend-diagnostic'; payload: BackendDiagnosticEvent }
      | { event: 'terminal:output'; payload: PtyOutputEvent }
      | { event: 'terminal:closed'; payload: PtyClosedEvent }
    ))
export type SectionConfig = { name: string; enabled: boolean; instructionOverride?: string }
export type SectionInfo = {
  name: string
  displayName: string
  description: string
  category: string
  isInstruction: boolean
}
export type SectionSettingsData = { enabled: boolean; instructionOverride?: string }
export type StackMetadataData = {
  stackId: number
  name: string
  description: string
  philosophy: string
  visualIdentity: VisualIdentityData
  whenToUse: string[]
  disciplineCount: number
  characteristics: string[]
}
export type SubsystemComment = {
  id: number
  category: string
  discipline?: string
  agentTaskId?: number
  body: string
  summary?: string
  reason?: string
  sourceIteration?: number
  created?: string
  updated?: string
}
export type SubsystemCommentData = {
  id: number
  category: string
  discipline?: string
  agentTaskId?: number
  body: string
  summary?: string
  reason?: string
  sourceIteration?: number
  created?: string
  updated?: string
}
export type SubsystemData = {
  id: number
  name: string
  displayName: string
  acronym: string
  description?: string
  created?: string
  status: string
  comments: SubsystemCommentData[]
}
export type SubsystemStatus = 'active' | 'archived'
export type SubsystemsCommentAddArgs = {
  subsystemName: string
  category: string
  discipline?: string
  agentTaskId?: number
  body: string
  summary?: string
  reason?: string
  sourceIteration?: number
}
export type SubsystemsCommentDeleteArgs = { subsystemName: string; commentId: number }
export type SubsystemsCommentUpdateArgs = {
  subsystemName: string
  commentId: number
  body: string
  summary?: string
  reason?: string
}
export type SubsystemsCreateArgs = { name: string; displayName: string; acronym: string; description?: string }
export type SubsystemsDeleteArgs = { name: string }
export type SubsystemsUpdateArgs = { name: string; displayName: string; acronym: string; description?: string }
export type Task = {
  id: number
  subsystem: string
  discipline: string
  title: string
  description?: string
  status: TaskStatus
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  created?: string
  updated?: string
  completed?: string
  acceptanceCriteria: string[]
  contextFiles: string[]
  outputArtifacts: string[]
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  pseudocode?: string
  enrichedAt?: string
  signals: TaskSignal[]
  subsystemDisplayName: string
  subsystemAcronym: string
  disciplineDisplayName: string
  disciplineAcronym: string
  disciplineIcon: string
  disciplineColor: string
}
export type TaskListItem = {
  id: number
  subsystem: string
  discipline: string
  title: string
  description?: string
  status: TaskStatus
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  acceptanceCriteriaCount: number
  signalCount: number
  provenance?: TaskProvenance
  subsystemDisplayName: string
  subsystemAcronym: string
  disciplineDisplayName: string
  disciplineAcronym: string
  disciplineIcon: string
  disciplineColor: string
}
export type TaskProvenance = 'agent' | 'human' | 'system'
export type TaskSignal = {
  id: number
  author: string
  body: string
  created?: string
  sessionId?: string
  signalVerb?: string
  parentSignalId?: number
  priority?: string
  summary?: string
  remaining?: string
  reason?: string
  question?: string
  what?: string
  on?: string
  blocking?: boolean
  severity?: string
  category?: string
  kind?: string
  scope?: string
  preferred?: string
  options?: string[]
  rationale?: string
  why?: string
  detail?: string
  text?: string
  answer?: string
}
export type TaskSignalComment = {
  id: number
  signalId: number
  sessionId?: string
  authorType: string
  body: string
  created?: string
}
export type TaskSignalCommentCreateInput = { signalId: number; sessionId?: string; authorType: string; body: string }
export type TaskSignalSummary = {
  pendingAsks: number
  flagCount: number
  maxFlagSeverity?: string
  lastClosingVerb?: string
  sessionCount: number
  learnedCount: number
}
export type TaskStatus = 'draft' | 'pending' | 'in_progress' | 'done' | 'blocked' | 'skipped'
export type TaskTemplate = {
  id: number
  disciplineId: number
  title: string
  description?: string
  priority?: Priority
  hints?: string
  estimatedTurns?: number
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
  pseudocode?: string
  created?: string
  updated?: string
  pulledCount: number
}
export type TasksAskAnswerArgs = { signalId: number; answer: string }
export type TasksCommentReplyAddArgs = { taskId: number; parentCommentId: number; priority?: string; body: string }
export type TasksCreateArgs = {
  subsystem: string
  discipline: string
  title: string
  description?: string
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  acceptanceCriteria: string[]
  contextFiles: string[]
  outputArtifacts: string[]
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
}
export type TasksDeleteArgs = { id: number }
export type TasksGetArgs = { id: number }
export type TasksSetStatusArgs = { id: number; status: string }
export type TasksSignalAddArgs = {
  taskId: number
  discipline?: string
  agentTaskId?: number
  priority?: string
  body: string
}
export type TasksSignalCommentDeleteArgs = { commentId: number }
export type TasksSignalCommentUpdateArgs = { commentId: number; body: string }
export type TasksSignalCommentsListArgs = { signalId: number }
export type TasksSignalDeleteArgs = { taskId: number; signalId: number }
export type TasksSignalSummariesGetArgs = { taskIds: number[] }
export type TasksSignalUpdateArgs = { taskId: number; signalId: number; body: string }
export type TasksUpdateArgs = {
  id: number
  subsystem: string
  discipline: string
  title: string
  description?: string
  priority?: Priority
  tags: string[]
  dependsOn: number[]
  acceptanceCriteria: string[]
  contextFiles: string[]
  outputArtifacts: string[]
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  agent?: string
  model?: string
  effort?: string
  thinking?: boolean
}
export type TerminalAgent = 'codex' | 'claude' | 'shell'
export type TerminalBridgeEmitSystemMessageArgs = { sessionId: string; text: string }
export type TerminalBridgeLaunchDefaults = {
  agent?: TerminalAgent
  model?: string
  effort?: string
  thinking?: boolean
  permissionLevel?: string
}
export type TerminalBridgeLaunchSource = 'task' | 'discipline' | 'default' | 'unset'
export type TerminalBridgeListModelFormTreeResult = { providers: TerminalBridgeListModelsResult[] }
export type TerminalBridgeListModelsResult = { agent: string; models: TerminalBridgeModelOption[] }
export type TerminalBridgeModelOption = {
  name: string
  display: string
  description: string
  sessionModel?: string
  effortOptions: string[]
}
export type TerminalBridgeReplayOutputArgs = { sessionId: string; afterSeq: number; limit: number }
export type TerminalBridgeReplayOutputChunk = { seq: number; data: string }
export type TerminalBridgeReplayOutputResult = {
  chunks: TerminalBridgeReplayOutputChunk[]
  hasMore: boolean
  truncated: boolean
  truncatedUntilSeq: number
}
export type TerminalBridgeResizeArgs = { sessionId: string; cols: number; rows: number }
export type TerminalBridgeResolveTaskLaunchArgs = { taskId: number; defaults: TerminalBridgeLaunchDefaults }
export type TerminalBridgeResolvedLaunchConfig = {
  agent?: TerminalAgent
  model?: string
  effort?: string
  thinking?: boolean
  permissionLevel?: string
  agentSource: TerminalBridgeLaunchSource
  modelSource: TerminalBridgeLaunchSource
  effortSource: TerminalBridgeLaunchSource
  thinkingSource: TerminalBridgeLaunchSource
  permissionLevelSource: TerminalBridgeLaunchSource
  modelSupportsEffort: boolean
}
export type TerminalBridgeSendInputArgs = { sessionId: string; data: number[] }
export type TerminalBridgeSetStreamModeArgs = { sessionId: string; mode: string }
export type TerminalBridgeStartHumanSessionArgs = {
  terminalSessionId: string
  kind: string
  taskId?: number
  agent?: TerminalAgent
  model?: string
  effort?: string
  permissionLevel?: string
  postStartPreamble?: string
  initPrompt?: string
  mcpMode?: TerminalMcpMode
  thinking?: boolean
}
export type TerminalBridgeStartHumanSessionResult = { agentSessionId: string; agentSessionNumber: number }
export type TerminalBridgeStartSessionArgs = {
  sessionId: string
  agent?: TerminalAgent
  mcpMode?: TerminalMcpMode
  model?: string
  effort?: string
  permissionLevel?: string
  thinking?: boolean
  postStartPreamble?: string
}
export type TerminalBridgeStartTaskSessionArgs = {
  sessionId: string
  taskId: number
  agent?: TerminalAgent
  model?: string
  effort?: string
  permissionLevel?: string
  thinking?: boolean
  postStartPreamble?: string
}
export type TerminalBridgeTerminateArgs = { sessionId: string }
export type TerminalMcpMode = 'interactive' | 'task_creation'
export type VisualIdentityData = { style: string; theme: string; tone: string; references: string }
