// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupStats = {
  name: string
  displayName: string
  total: number
  draft: number
  done: number
  pending: number
  inProgress: number
  blocked: number
  skipped: number
}
