// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerConfig = { name: string; command: string; args: Array<string>; env: { [key in string]: string } }
