// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionSettingsData } from './SectionSettingsData'

export type RecipeConfigInput = {
  name: string
  baseRecipe: string
  sectionOrder: Array<string>
  sections: { [key in string]: SectionSettingsData }
}
