// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskComment = {
  id: number
  author: string
  body: string
  created?: string
  session_id?: string
  signal_verb?: string
  signal_payload?: string
  signal_answered?: string
}
