// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskSignalSummary = {
  pendingAsks: number
  flagCount: number
  maxFlagSeverity?: string
  lastClosingVerb?: string
  sessionCount: number
  learnedCount: number
}
