// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from './Priority'
import type { TaskComment } from './TaskComment'
import type { TaskProvenance } from './TaskProvenance'
import type { TaskStatus } from './TaskStatus'

export type Task = {
  id: number
  feature: string
  discipline: string
  title: string
  description?: string
  status: TaskStatus
  priority?: Priority
  tags: Array<string>
  dependsOn: Array<number>
  blockedBy?: string
  created?: string
  updated?: string
  completed?: string
  acceptanceCriteria: Array<string>
  contextFiles: Array<string>
  outputArtifacts: Array<string>
  hints?: string
  estimatedTurns?: number
  provenance?: TaskProvenance
  pseudocode?: string
  enrichedAt?: string
  comments: Array<TaskComment>
  featureDisplayName: string
  featureAcronym: string
  disciplineDisplayName: string
  disciplineAcronym: string
  disciplineIcon: string
  disciplineColor: string
}
